// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniEShop.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniEShop.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    [Migration("20260719141537_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MiniEShop.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MiniEShop.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MiniEShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MiniEShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Telefon, bilgisayar ve aksesuarlar",
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Ev yaşam ürünleri",
                            Name = "Ev & Yaşam"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Giyim ve aksesuar",
                            Name = "Moda"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Spor ekipmanları",
                            Name = "Spor"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Roman, eğitim ve hobi kitapları",
                            Name = "Kitap"
                        });
                });

            modelBuilder.Entity("MiniEShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MiniEShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MiniEShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Aktif gürültü önleyici",
                            ImageUrl = "https://placehold.co/400x400?text=Kablosuz+Kulaklik",
                            Name = "Kablosuz Kulaklık",
                            Price = 3499m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Taşınabilir hoparlör",
                            ImageUrl = "https://placehold.co/400x400?text=Bluetooth+Hoparlor",
                            Name = "Bluetooth Hoparlör",
                            Price = 1799m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Fitness takip özellikli",
                            ImageUrl = "https://placehold.co/400x400?text=Akilli+Saat",
                            Name = "Akıllı Saat",
                            Price = 4299m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "RGB aydınlatmalı",
                            ImageUrl = "https://placehold.co/400x400?text=Mekanik+Klavye",
                            Name = "Mekanik Klavye",
                            Price = 2599m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "6400 DPI",
                            ImageUrl = "https://placehold.co/400x400?text=Gaming+Mouse",
                            Name = "Gaming Mouse",
                            Price = 999m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "1080p",
                            ImageUrl = "https://placehold.co/400x400?text=Web+Kamera",
                            Name = "Web Kamera",
                            Price = 1399m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "20000 mAh",
                            ImageUrl = "https://placehold.co/400x400?text=Powerbank",
                            Name = "Powerbank",
                            Price = 1199m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "128 GB",
                            ImageUrl = "https://placehold.co/400x400?text=USB+Bellek",
                            Name = "USB Bellek",
                            Price = 499m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "1 TB",
                            ImageUrl = "https://placehold.co/400x400?text=Harici+SSD",
                            Name = "Harici SSD",
                            Price = 3299m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "Alüminyum",
                            ImageUrl = "https://placehold.co/400x400?text=Laptop+Standi",
                            Name = "Laptop Standı",
                            Price = 799m,
                            StockQuantity = 41
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "2 metre",
                            ImageUrl = "https://placehold.co/400x400?text=HDMI+Kablo",
                            Name = "HDMI Kablo",
                            Price = 249m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 1,
                            Description = "15W",
                            ImageUrl = "https://placehold.co/400x400?text=Kablosuz+Sarj",
                            Name = "Kablosuz Şarj",
                            Price = 699m,
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 1,
                            Description = "27 inç IPS",
                            ImageUrl = "https://placehold.co/400x400?text=Monitor",
                            Name = "Monitör",
                            Price = 7499m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Description = "Filtre kahve",
                            ImageUrl = "https://placehold.co/400x400?text=Kahve+Makinesi",
                            Name = "Kahve Makinesi",
                            Price = 2499m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Description = "Sessiz çalışma",
                            ImageUrl = "https://placehold.co/400x400?text=Supurge",
                            Name = "Elektrikli Süpürge",
                            Price = 6999m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Description = "1000W",
                            ImageUrl = "https://placehold.co/400x400?text=Blender",
                            Name = "Blender",
                            Price = 1499m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Buharlı",
                            ImageUrl = "https://placehold.co/400x400?text=Utu",
                            Name = "Ütü",
                            Price = 1899m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "1800W",
                            ImageUrl = "https://placehold.co/400x400?text=Tost+Makinesi",
                            Name = "Tost Makinesi",
                            Price = 1699m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Cam demlik",
                            ImageUrl = "https://placehold.co/400x400?text=Cay+Makinesi",
                            Name = "Çay Makinesi",
                            Price = 2299m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "1.7L",
                            ImageUrl = "https://placehold.co/400x400?text=Su+Isitici",
                            Name = "Su Isıtıcı",
                            Price = 899m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 2,
                            Description = "Yağsız pişirme",
                            ImageUrl = "https://placehold.co/400x400?text=Air+Fryer",
                            Name = "Air Fryer",
                            Price = 4299m,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 2,
                            Description = "El mikseri",
                            ImageUrl = "https://placehold.co/400x400?text=Mikser",
                            Name = "Mikser",
                            Price = 799m,
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 2,
                            Description = "7 Parça",
                            ImageUrl = "https://placehold.co/400x400?text=Tencere+Seti",
                            Name = "Tencere Seti",
                            Price = 3999m,
                            StockQuantity = 11
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 2,
                            Description = "Granit",
                            ImageUrl = "https://placehold.co/400x400?text=Tava",
                            Name = "Tava",
                            Price = 699m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 2,
                            Description = "Çift kişilik",
                            ImageUrl = "https://placehold.co/400x400?text=Nevresim",
                            Name = "Nevresim Takımı",
                            Price = 1299m,
                            StockQuantity = 19
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 2,
                            Description = "Ortopedik",
                            ImageUrl = "https://placehold.co/400x400?text=Yastik",
                            Name = "Yastık",
                            Price = 499m,
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            Description = "LED",
                            ImageUrl = "https://placehold.co/400x400?text=Masa+Lambasi",
                            Name = "Masa Lambası",
                            Price = 599m,
                            StockQuantity = 27
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Fon perde",
                            ImageUrl = "https://placehold.co/400x400?text=Perde",
                            Name = "Perde",
                            Price = 899m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 2,
                            Description = "160x230",
                            ImageUrl = "https://placehold.co/400x400?text=Hali",
                            Name = "Halı",
                            Price = 2599m,
                            StockQuantity = 9
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "5 Parça",
                            ImageUrl = "https://placehold.co/400x400?text=Banyo+Seti",
                            Name = "Banyo Seti",
                            Price = 999m,
                            StockQuantity = 13
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            Description = "Katlanabilir",
                            ImageUrl = "https://placehold.co/400x400?text=Camasir+Sepeti",
                            Name = "Çamaşır Sepeti",
                            Price = 399m,
                            StockQuantity = 21
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Plastik",
                            ImageUrl = "https://placehold.co/400x400?text=Saklama+Kutusu",
                            Name = "Saklama Kutusu",
                            Price = 199m,
                            StockQuantity = 48
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 2,
                            Description = "Pedallı",
                            ImageUrl = "https://placehold.co/400x400?text=Cop+Kovasi",
                            Name = "Çöp Kovası",
                            Price = 449m,
                            StockQuantity = 26
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Metal",
                            ImageUrl = "https://placehold.co/400x400?text=Askilik",
                            Name = "Askılık",
                            Price = 349m,
                            StockQuantity = 34
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Duvar rafı",
                            ImageUrl = "https://placehold.co/400x400?text=Raf",
                            Name = "Raf",
                            Price = 699m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 2,
                            Description = "Dekoratif",
                            ImageUrl = "https://placehold.co/400x400?text=Ayna",
                            Name = "Ayna",
                            Price = 999m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Description = "Kokulu",
                            ImageUrl = "https://placehold.co/400x400?text=Mum+Seti",
                            Name = "Mum Seti",
                            Price = 299m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Modern",
                            ImageUrl = "https://placehold.co/400x400?text=Duvar+Saati",
                            Name = "Duvar Saati",
                            Price = 799m,
                            StockQuantity = 17
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 2,
                            Description = "Seramik",
                            ImageUrl = "https://placehold.co/400x400?text=Vazo",
                            Name = "Vazo",
                            Price = 549m,
                            StockQuantity = 23
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Çift kişilik",
                            ImageUrl = "https://placehold.co/400x400?text=Battaniye",
                            Name = "Battaniye",
                            Price = 1199m,
                            StockQuantity = 16
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 3,
                            Description = "Pamuklu",
                            ImageUrl = "https://placehold.co/400x400?text=Tisort",
                            Name = "Tişört",
                            Price = 399m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 3,
                            Description = "Slim Fit",
                            ImageUrl = "https://placehold.co/400x400?text=Kot+Pantolon",
                            Name = "Kot Pantolon",
                            Price = 899m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            Description = "Koşu ayakkabısı",
                            ImageUrl = "https://placehold.co/400x400?text=Spor+Ayakkabi",
                            Name = "Spor Ayakkabı",
                            Price = 2199m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Description = "Mevsimlik",
                            ImageUrl = "https://placehold.co/400x400?text=Ceket",
                            Name = "Ceket",
                            Price = 1699m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 3,
                            Description = "Günlük kullanım",
                            ImageUrl = "https://placehold.co/400x400?text=Sirt+Cantasi",
                            Name = "Sırt Çantası",
                            Price = 799m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Kaymaz yüzey",
                            ImageUrl = "https://placehold.co/400x400?text=Yoga+Mati",
                            Name = "Yoga Matı",
                            Price = 599m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 4,
                            Description = "10 kg",
                            ImageUrl = "https://placehold.co/400x400?text=Dambil+Seti",
                            Name = "Dambıl Seti",
                            Price = 1299m,
                            StockQuantity = 14
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 4,
                            Description = "5 Numara",
                            ImageUrl = "https://placehold.co/400x400?text=Futbol+Topu",
                            Name = "Futbol Topu",
                            Price = 699m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 5,
                            Description = "Yazılım geliştirme",
                            ImageUrl = "https://placehold.co/400x400?text=Clean+Code",
                            Name = "Clean Code",
                            Price = 799m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "GoF",
                            ImageUrl = "https://placehold.co/400x400?text=Design+Patterns",
                            Name = "Design Patterns",
                            Price = 899m,
                            StockQuantity = 12
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MiniEShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MiniEShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniEShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MiniEShop.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiniEShop.Models.Cart", b =>
                {
                    b.HasOne("MiniEShop.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniEShop.Models.CartItem", b =>
                {
                    b.HasOne("MiniEShop.Models.Cart", "Cart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniEShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniEShop.Models.Order", b =>
                {
                    b.HasOne("MiniEShop.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MiniEShop.Models.OrderItem", b =>
                {
                    b.HasOne("MiniEShop.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniEShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniEShop.Models.Product", b =>
                {
                    b.HasOne("MiniEShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniEShop.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MiniEShop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniEShop.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
